echo '[tool.poetry]
name = "generate-nametag"
version = "0.1.0"
description = ""

authors = ["Jade Abbott <jade.abbott@example.com>"]


               
[tool.poetry.dependencies]
python = "^3.8"
streamlit = "^1.0.0",
Pillow = "^8.0.0"

[tool.poetry.scripts]
app = "app:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"' > pyproject.toml